### ISSUE TITLE
32 bit typo in comment

### ISSUE THREAD

**Issue by 8dcc** [Robert-van-Engelen/tinylisp#11]
Inside the commented file, in the `ord()` function, there is the following comment:

https://github.com/Robert-van-Engelen/tinylisp/blob/7ee0feb65e3086eb94e7dd49009d61aeebed5176/src/tinylisp-commented.c#L59-L61

Shouldn't it be "64 bit unsigned integer"?

This is also what appears in your (*amazing*) article:
> ```c
> /*** with NaN Boxing ***/
> L box(I t,I i) { L x; *(uint64_t*)&x = (uint64_t)t<<48|i; return x; }
> I ord(L x) { return *(uint64_t*)&x; }
> ```
> [...] The ord function unboxes the unsigned integer (ordinal) of a tagged float.

**Comment by genivia-inc** [comment]
Thank you for your feedback. The `I` type is a 32 bit `unsigned`, so we narrow the result with `ord()` to a 32 bit unsigned integer to get the untagged "ordinal" value. Note that `x` is cast to a 64 bit unsigned integer first (from a double float). But we should narrow to toss the tag. A `return (uint32_t)*(uint64_t*)&x;` would make this explicit or `return *(uint64_t*)&x & 0xffffffff;`. Sometimes things get less clear when cramping C code, but it's still valid C code.

**Comment by 8dcc** [comment]
I understand better now, thank you for the quick reply. My mistake was looking at the `box()` function as if it was a macro.
