### ISSUE TITLE
Dynamic memory

### ISSUE THREAD

**Issue by stevefan1999-personal** [Robert-van-Engelen/tinylisp#2]
It would be better if we can use more than the static amount of memory. I tried implementing it but it just crashes:
```c
// L *cell;
void expand() { 
	// allocate a heap with twice the size
	cell = realloc(cell, 2 * N * sizeof(L));
	// move the old data to the higher half
	memmove(cell + N, cell, N * sizeof(L));
	// clear lower half
	memset(cell, 0, N);
	// advance stack and heap pointer
	sp += N, hp += N;
	// expand the base stack size
	N *= 2;
}
L cons(L x, L y) { cell[(--sp <= 0 ? expand() : 0), sp] = x; cell[(--sp <= 0 ? expand() : 0), sp] = y;  if (hp > sp - 1 << 3) abort(); return box(CONS, sp); }
```
I think the main reason is that the old cell locations are invalidated and hence read wrong data. Perhaps this could be solved with a stack pointing to a (pinned) cell indirection pointer that does not move.

**Comment by Robert-van-Engelen** [comment]
The stack grows downward. If the stack grows upward, then you don't need to change the cons pairs in the cells. Or index the cells from the top of the stack with `N - <index>`.
