### ISSUE TITLE
Type PDF page 14

### ISSUE THREAD

**Issue by Luv2C0d3** [Robert-van-Engelen/tinylisp#9]
At the top of the page, where it says:
"Environments are searched with the assoc function given an **atom a** and an environment e:"
Should say:
"Environments are searched with the assoc function given an **atom v** and anenvironment e:"

The reason is that the example function that follows uses **v**

```
L assoc(L v,L e) {
  while (T(e) == CONS && !equ(v,car(car(e)))) e = cdr(e);
  return T(e) == CONS ? cdr(car(e)) : err;
}
```

**Comment by Robert-van-Engelen** [comment]
Thanks!
